export function createHistoryState(trendWindowHours) {
  return {
    controlReplayTab: "status",
    controlReplayWindow: "last24",
    controlReplayPeriodMenuOpen: false,
    controlReplayCustomPeriodOpen: false,
    controlReplayCustomStart: "",
    controlReplayCustomEnd: "",
    controlReplayCustomPeriodError: "",
    controlReplaySelectedEpisode: "",
    controlReplaySupportDetailsItemId: "",
    controlReplayGraphMinute: 1000,
    controlReplayScrubbing: false,
    decisionLog: null,
    decisionLogError: "",
    decisionLogSignature: "",
    decisionLogLastFetchAt: 0,
    decisionLogFetchPromise: null,
    decisionLogStorageMetadata: {},
    decisionLogStorageMetadataError: "",
    decisionLogStorageMetadataSignature: "",
    decisionLogStorageMetadataLastFetchAt: 0,
    decisionLogStorageMetadataFetchPromise: null,
    trendWindowHours,
    trendHistoryRaw: "",
    trendHistoryError: "",
    trendHistorySignature: "",
    trendHistoryNowMs: Number.NaN,
    trendHistoryLastFetchAt: 0,
    trendHistoryFetchPromise: null,
    trendHistoryMetadata: {},
    trendHistoryMetadataError: "",
    trendHistoryMetadataSignature: "",
    trendHistoryMetadataLastFetchAt: 0,
    trendHistoryMetadataFetchPromise: null,
    energyHistoryRaw: "",
    energyHistoryError: "",
    energyHistorySignature: "",
    energyHistoryNowMs: Number.NaN,
    energyHistoryLastFetchAt: 0,
    energyHistoryRequestQuery: "",
    energyHistoryFetchQuery: "",
    energyHistoryFetchPromise: null,
    energyHistoryCsrfToken: "",
    energyHistoryView: "day",
    energyHistoryImportFileName: "",
    energyHistoryImportSource: "",
    energyHistoryImportRange: "",
    energyHistoryImportRecords: [],
    energyHistoryImportHourRecords: [],
    energyHistoryImportDuplicateCount: 0,
    energyHistoryImportSkippedCount: 0,
    energyHistoryImportInvalidCount: 0,
    energyHistoryImportUnsupportedCount: 0,
    energyHistoryImportBusy: false,
    energyHistoryImportProgressPercent: 0,
    energyHistoryImportError: "",
    energyHistoryImportNotice: "",
    energyHistoryExportMode: "days_and_hours",
    energyHistoryExportBusy: false,
    energyHistoryExportError: "",
    energyHistoryExportNotice: "",
    settingsStorageAdvancedOpen: false,
    settingsStorageDetailsOpen: false,
    settingsStoragePage: "overview",
    energyHistoryPeriodSelection: { day: "", week: "", month: "", year: "" },
  };
}

export function createDiagnosticsState(debugRecordingAcknowledgedId) {
  return {
    webServerLogSource: null,
    webServerLogConnected: false,
    webServerLogEnabled: null,
    webServerLogError: "",
    webServerLogHistoryLoading: false,
    webServerLogHistoryError: "",
    webServerLogHistoryRequestToken: 0,
    webServerLogHistoryLoaded: false,
    webServerLogCsrfToken: "",
    webServerLogHistoryNeedsReconcile: false,
    webServerLogScrollRestoreToken: 0,
    cm100CommissioningScrollRestoreToken: 0,
    serviceTaskModalScrollRestoreToken: 0,
    historyStorageModalScrollRestoreToken: 0,
    quickStartScrollRestoreToken: 0,
    quickStartCicFeedUrlDraft: null,
    quickStartThermostatSourceDraft: null,
    quickStartSetupDraft: "",
    quickStartSetupConfirmed: false,
    webServerLogCopyMessage: "",
    webServerLogCopyError: "",
    webServerLogRecentTail: [],
    webServerLogRecentAnchorAt: 0,
    webServerLogEntries: [],
    debugRecordingActive: false,
    debugRecordingError: "",
    debugRecordingNotice: "",
    debugRecordingBusy: false,
    debugRecordingSelectedMinutes: 15,
    debugRecordingDeviceStatus: null,
    debugRecordingAcknowledgedId,
    debugRecordingDeviceBundle: null,
    debugRecordingDevicePollTimer: null,
    oduEepromDumpStatuses: {},
    oduEepromDumpBusyHp: 0,
    oduEepromDumpError: "",
    oduEepromDumpNotice: "",
    oduEepromDumpLastFetchAt: 0,
    oduEepromDumpFetchPromise: null,
    oduEepromDumpPollTimer: null,
  };
}

export function createSettingsState() {
  return {
    complete: false,
    lastKnownInstallationTopology: "",
    quickStartModalOpen: true,
    loadingEntities: true,
    entities: {},
    optionalMissingEntities: {},
    renderedAppView: "",
    renderedSettingsGroup: "",
    settingsPageScrollRestoreToken: 0,
    settingsInfoOpen: "",
    settingsAdvancedOpen: {},
    pendingControlModeOverride: "",
    installationMonitoringDetailsOpen: false,
    compressorLimitsOpen: false,
    integrationDiagnosticsOpen: false,
    oduRuntimeFrequencyDetailsOpen: false,
    usageTelemetryDetailsOpen: false,
    usageTelemetryPreviewPayload: null,
    usageTelemetryPreviewSurface: "",
    installationMonitoringProblemSignature: "",
    incidentMonitoringSnapshot: null,
    incidentMonitoringError: "",
    incidentMonitoringUnsupported: false,
    incidentMonitoringFailureCount: 0,
    incidentMonitoringSignature: "",
    incidentMonitoringRenderPending: false,
    incidentMonitoringLastFetchAt: 0,
    incidentMonitoringFetchPromise: null,
    incidentAction: {
      hp: 0,
      kind: "",
      requestId: 0,
      pending: false,
      ok: null,
      result: "",
    },
    settingsInteractionLock: false,
    settingsRenderSignature: "",
    settingsBackupDraft: null,
    settingsBackupMqttPassword: "",
    settingsBackupRestoreResult: null,
    settingsBackupError: "",
    settingsBackupBusy: false,
    pendingCommissioningCm100Start: false,
    pendingBoilerPowerTestStart: false,
    pendingFlowAutotuneStart: false,
    pendingAirPurgeStart: false,
    pendingManualFlowStart: false,
    pendingManualHpStart: false,
    pendingHpWaterCalibrationStart: false,
    commissioningTaskLock: "",
    commissioningBoilerHeatPowerDisplay: "",
    headerRenderSignature: "",
    drafts: {},
    inputDrafts: {},
    focusedField: "",
  };
}

export function createSecurityState() {
  return {
    authStatus: null,
    authDraftUsername: "",
    authDraftCurrentPassword: "",
    authDraftNewPassword: "",
    authDraftConfirmPassword: "",
    authBusy: false,
    authNotice: "",
    authError: "",
    apiSecurityStatus: null,
    apiSecurityBusy: false,
    apiSecurityNotice: "",
    apiSecurityError: "",
    mqttStatus: null,
    mqttDraftEnabled: false,
    mqttDraftBroker: "",
    mqttDraftPort: "1883",
    mqttDraftUsername: "",
    mqttDraftPassword: "",
    mqttDraftClearPassword: false,
    mqttDraftDirty: false,
    mqttBusy: false,
    mqttNotice: "",
    mqttError: "",
    mqttCopiedTopicKey: "",
    mqttCopiedTopicTimer: null,
    mqttExpandedTopicKey: "",
    mqttInputToggleBusyKey: "",
    mqttRetainedToggleBusyKey: "",
    mqttSensorsModalRenderSignature: "",
  };
}

export function createFirmwareState() {
  return {
    updateCheckBusy: false,
    updateInstallBusy: false,
    updateInstallTargetVersion: "",
    updateInstallPhaseHint: "",
    updateInstallProgressHint: Number.NaN,
    updateInstallStatusPollObserved: false,
    updateInstallSuccessfulPhaseObserved: false,
    updateInstallResumedAfterReload: false,
    updateInstallMode: "",
    updateInstallTargetConnection: "",
    updateInstallTargetTopology: "",
    firmwareDowngradeConfirmedVersion: "",
    firmwareAdvancedOpen: false,
    firmwareConnectionSwitchOpen: false,
    firmwareConnectionSwitchConfirmed: false,
    firmwareTopologySwitchOpen: false,
    firmwareTopologySwitchConfirmed: false,
    updateInstallCompleted: false,
    updateInstallCompletedVersion: "",
    updateManualUploadOpen: false,
    updateManualUploadFile: null,
    updateManualUploadFileName: "",
    updateManualUploadError: "",
    updateTestFirmwareOpen: false,
    updateTestFirmwarePr: "",
    updateTestFirmwareConfirmed: false,
    updateTestFirmwareError: "",
    updateTestFirmwareBuild: null,
    pauseResumeDraft: "",
  };
}

export function createMotionState(reducedMotion) {
  return {
    draggingCurveKey: "",
    motionFrame: 0,
    motionStartedAt: 0,
    reducedMotion,
    motionPreferenceMedia: null,
    motionPreferenceListener: null,
    motionTargets: { pipeFlows: [], fanBlades: [] },
  };
}
